apiVersion: v1
kind: Service
metadata:
  name: {{ include "fakturo.rabbitmqName" . }}
  labels:
    {{- include "fakturo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
  selector:
    app: rabbitmq
