{{- if .Values.rpcServer.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fakturo.rpcServerName" . }}
data:
  {{- with .Values.rpcServer.configMap }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
